// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/me/bookmarks": {
            "get": {
                "security": [
                    {
                        "KeycloakAuth": []
                    }
                ],
                "description": "Возвращает все вопросы, добавленные пользователем в закладки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "Список закладок",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_devprep_backend_internal_model.Bookmark"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/me/history": {
            "get": {
                "security": [
                    {
                        "KeycloakAuth": []
                    }
                ],
                "description": "Возвращает просмотренные вопросы, отсортированные по времени",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "История просмотров",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_devprep_backend_internal_model.ViewHistory"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/me/progress": {
            "get": {
                "security": [
                    {
                        "KeycloakAuth": []
                    }
                ],
                "description": "Возвращает список всех вопросов со статусами изучения",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "progress"
                ],
                "summary": "Весь прогресс пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_devprep_backend_internal_model.UserProgress"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/me/progress/by-topic": {
            "get": {
                "security": [
                    {
                        "KeycloakAuth": []
                    }
                ],
                "description": "Возвращает количество изученных, требующих повторения и незнакомых вопросов по каждой теме",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "progress"
                ],
                "summary": "Агрегированный прогресс по темам",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_devprep_backend_internal_model.TopicProgress"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/questions": {
            "get": {
                "description": "Возвращает вопросы с фильтрацией по теме, тегу и уровню сложности",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Список вопросов с пагинацией",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug топика",
                        "name": "topic",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Slug тега",
                        "name": "tag",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "junior",
                            "middle",
                            "senior"
                        ],
                        "type": "string",
                        "description": "Уровень сложности",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Размер страницы",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_devprep_backend_internal_model.PaginatedQuestions"
                        }
                    }
                }
            }
        },
        "/questions/{slug}": {
            "get": {
                "description": "Возвращает полный вопрос с ответом, темой и тегами",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Вопрос по slug",
                "parameters": [
                    {
                        "type": "string",
                        "example": "what-is-goroutine",
                        "description": "Slug вопроса",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_devprep_backend_internal_model.QuestionDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/questions/{slug}/bookmark": {
            "get": {
                "security": [
                    {
                        "KeycloakAuth": []
                    }
                ],
                "description": "Проверяет, добавлен ли вопрос в закладки текущим пользователем",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "Статус закладки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug вопроса",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.bookmarkStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "KeycloakAuth": []
                    }
                ],
                "description": "Если закладки нет — создаёт, если есть — удаляет. Возвращает итоговый статус.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "Добавить / убрать закладку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug вопроса",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.bookmarkStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/questions/{slug}/progress": {
            "get": {
                "security": [
                    {
                        "KeycloakAuth": []
                    }
                ],
                "description": "Возвращает статус изучения вопроса текущим пользователем",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "progress"
                ],
                "summary": "Прогресс по конкретному вопросу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug вопроса",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_devprep_backend_internal_model.UserProgress"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "KeycloakAuth": []
                    }
                ],
                "description": "Устанавливает статус изучения для вопроса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "progress"
                ],
                "summary": "Обновить статус изучения вопроса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug вопроса",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Статус",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateProgressRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/questions/{slug}/view": {
            "post": {
                "security": [
                    {
                        "KeycloakAuth": []
                    }
                ],
                "description": "Фиксирует факт просмотра вопроса.",
                "tags": [
                    "history"
                ],
                "summary": "Записать просмотр вопроса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug вопроса",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "Возвращает все доступные теги, отсортированные по имени",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Список тегов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_devprep_backend_internal_model.Tag"
                            }
                        }
                    }
                }
            }
        },
        "/topics": {
            "get": {
                "description": "Возвращает все темы, отсортированные по sort_order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topics"
                ],
                "summary": "Список тем",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                            }
                        }
                    }
                }
            }
        },
        "/topics/{slug}": {
            "get": {
                "description": "Возвращает тему и связанные вопросы, опционально фильтруя по уровню",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topics"
                ],
                "summary": "Тема со списком вопросов",
                "parameters": [
                    {
                        "type": "string",
                        "example": "golang",
                        "description": "Slug темы",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "junior",
                            "middle",
                            "senior"
                        ],
                        "type": "string",
                        "description": "Уровень сложности",
                        "name": "level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_devprep_backend_internal_model.TopicWithQuestions"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_devprep_backend_internal_model.Bookmark": {
            "type": "object",
            "properties": {
                "bookmarked_at": {
                    "type": "string"
                },
                "level": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Level"
                },
                "question_id": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                }
            }
        },
        "github_com_devprep_backend_internal_model.Level": {
            "type": "string",
            "enum": [
                "junior",
                "middle",
                "senior"
            ],
            "x-enum-varnames": [
                "LevelJunior",
                "LevelMiddle",
                "LevelSenior"
            ]
        },
        "github_com_devprep_backend_internal_model.PaginatedQuestions": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devprep_backend_internal_model.QuestionListItem"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Pagination"
                }
            }
        },
        "github_com_devprep_backend_internal_model.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_devprep_backend_internal_model.ProgressStatus": {
            "type": "string",
            "enum": [
                "learned",
                "need_review",
                "dont_know"
            ],
            "x-enum-varnames": [
                "StatusLearned",
                "StatusNeedReview",
                "StatusDontKnow"
            ]
        },
        "github_com_devprep_backend_internal_model.QuestionDetail": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Level"
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devprep_backend_internal_model.Tag"
                    }
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                },
                "topic_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_devprep_backend_internal_model.QuestionListItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "level": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Level"
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devprep_backend_internal_model.Tag"
                    }
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                }
            }
        },
        "github_com_devprep_backend_internal_model.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "github_com_devprep_backend_internal_model.Topic": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "github_com_devprep_backend_internal_model.TopicProgress": {
            "type": "object",
            "properties": {
                "dont_know": {
                    "type": "integer"
                },
                "learned": {
                    "type": "integer"
                },
                "need_review": {
                    "type": "integer"
                },
                "topic": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_devprep_backend_internal_model.TopicWithQuestions": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devprep_backend_internal_model.QuestionListItem"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "github_com_devprep_backend_internal_model.UserProgress": {
            "type": "object",
            "properties": {
                "level": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Level"
                },
                "question_id": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.ProgressStatus"
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_devprep_backend_internal_model.ViewHistory": {
            "type": "object",
            "properties": {
                "level": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Level"
                },
                "question_id": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                },
                "viewed_at": {
                    "type": "string"
                }
            }
        },
        "internal_handler.bookmarkStatusResponse": {
            "type": "object",
            "properties": {
                "bookmarked": {
                    "type": "boolean"
                }
            }
        },
        "internal_handler.errorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "internal_handler.updateProgressRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "KeycloakAuth": {
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "http://KEYCLOAK_AUTH_URL",
            "tokenUrl": "http://KEYCLOAK_TOKEN_URL",
            "scopes": {
                "microprofile-jwt": "",
                "openid": ""
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DevPrep API",
	Description:      "REST API для подготовки к техническому интервью.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
