// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/questions": {
            "get": {
                "description": "Возвращает вопросы с фильтрацией по теме, тегу и уровню сложности",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Список вопросов с пагинацией",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug топика",
                        "name": "topic",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Slug тега",
                        "name": "tag",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "junior",
                            "middle",
                            "senior"
                        ],
                        "type": "string",
                        "description": "Уровень сложности",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Размер страницы",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_devprep_backend_internal_model.PaginatedQuestions"
                        }
                    }
                }
            }
        },
        "/questions/{slug}": {
            "get": {
                "description": "Возвращает полный вопрос с ответом, темой и тегами",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Вопрос по slug",
                "parameters": [
                    {
                        "type": "string",
                        "example": "what-is-goroutine",
                        "description": "Slug вопроса",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_devprep_backend_internal_model.QuestionDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "Возвращает все доступные теги, отсортированные по имени",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Список тегов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_devprep_backend_internal_model.Tag"
                            }
                        }
                    }
                }
            }
        },
        "/topics": {
            "get": {
                "description": "Возвращает все темы, отсортированные по sort_order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topics"
                ],
                "summary": "Список тем",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                            }
                        }
                    }
                }
            }
        },
        "/topics/{slug}": {
            "get": {
                "description": "Возвращает тему и связанные вопросы, опционально фильтруя по уровню",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topics"
                ],
                "summary": "Тема со списком вопросов",
                "parameters": [
                    {
                        "type": "string",
                        "example": "golang",
                        "description": "Slug темы",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "junior",
                            "middle",
                            "senior"
                        ],
                        "type": "string",
                        "description": "Уровень сложности",
                        "name": "level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_devprep_backend_internal_model.TopicWithQuestions"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_devprep_backend_internal_model.Level": {
            "type": "string",
            "enum": [
                "junior",
                "middle",
                "senior"
            ],
            "x-enum-varnames": [
                "LevelJunior",
                "LevelMiddle",
                "LevelSenior"
            ]
        },
        "github_com_devprep_backend_internal_model.PaginatedQuestions": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devprep_backend_internal_model.QuestionListItem"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Pagination"
                }
            }
        },
        "github_com_devprep_backend_internal_model.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_devprep_backend_internal_model.QuestionDetail": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Level"
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devprep_backend_internal_model.Tag"
                    }
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                },
                "topic_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_devprep_backend_internal_model.QuestionListItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "level": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Level"
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devprep_backend_internal_model.Tag"
                    }
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "$ref": "#/definitions/github_com_devprep_backend_internal_model.Topic"
                }
            }
        },
        "github_com_devprep_backend_internal_model.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "github_com_devprep_backend_internal_model.Topic": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "github_com_devprep_backend_internal_model.TopicWithQuestions": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devprep_backend_internal_model.QuestionListItem"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.errorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DevPrep API",
	Description:      "REST API для подготовки к техническому интервью.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
